### ISSUE TITLE
MyGUIEngine build fails: framework not found FREETYPE

### ISSUE THREAD

**Issue by emillaine** [OpenMW/openmw-deps-mac#13]
- OS X 10.11.6
- Xcode 8 beta 6
- CMake 3.6.1
- openmw-deps-mac [`e070069`](https://github.com/OpenMW/openmw-deps-mac/tree/e0700694624f7efeec9d69a0cccd92c043e34081)

Followed the instructions in the readme and got the following error when running `make`:

```
[ 97%] Linking CXX shared library ../lib/libMyGUIEngine.dylib
ld: framework not found FREETYPE
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[5]: *** [lib/libMyGUIEngine.3.2.3.dylib] Error 1
make[4]: *** [MyGUIEngine/CMakeFiles/MyGUIEngine.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [src/mygui-prefix/src/mygui-stamp/mygui-build] Error 2
make[1]: *** [src/CMakeFiles/mygui.dir/all] Error 2
make: *** [all] Error 2
make  1355.52s user 127.88s system 93% cpu 26:28.86 total
```

I have freetype installed via homebrew.

**Comment by nikolaykasyanov** [comment]
Thanks for the report!

Freetype is supposed to be built before MyGUI, you don't have to install it separately.

I'll try to figure out what's happening when there's Freetype from Homebrew.

**Comment by nikolaykasyanov** [comment]
By the way, do you use sandboxed calls to cmake and make? Please refer to "Caveats" section of the readme for details.

**Comment by emillaine** [comment]
Yeah, I tried the sandboxed way after this failed, but it failed with the same error as well.

**Comment by emillaine** [comment]
Hmm, I now uninstalled the homebrew freetype and got a different error:

```
[ 92%] Building CXX object src/osgPlugins/freetype/CMakeFiles/osgdb_freetype.dir/FreeTypeFont.cpp.o
In file included from /Users/emlai/Documents/Code/openmw-deps-mac/src/openscenegraph/src/osgPlugins/freetype/FreeTypeFont.cpp:14:
In file included from /Users/emlai/Documents/Code/openmw-deps-mac/src/openscenegraph/src/osgPlugins/freetype/FreeTypeFont.h:19:
/Library/Frameworks/Mono.framework/Headers/ft2build.h:56:10: fatal error: 'freetype/config/ftheader.h' file not
      found
#include <freetype/config/ftheader.h>
         ^
```

**Comment by nikolaykasyanov** [comment]
@emlai are you rebuilding from scratch, i.e. purging build dir completely?

**Comment by emillaine** [comment]
Yes.

**Comment by emlai** [comment]
I downgraded to Xcode 7.3.1 and now it works.

**Comment by emillaine** [comment]
This seems to be the same issue as (or related to) https://github.com/rougier/freetype-gl/issues/76.

**Comment by nikolaykasyanov** [comment]
Thanks for the update. Does downgrading to 7.3.1 help?

**Comment by emillaine** [comment]
No, same error. Also tried with Xcode 8 GM seed, no luck.

**Comment by emillaine** [comment]
It works if I remove `freetype.framework` from `/Library/Frameworks`.

**Comment by nikolaykasyanov** [comment]
@emlai: thanks for the update! I'll check if I can modify sandbox config to avoid that in the future.
