### ISSUE TITLE
Prebuilt dependencies result in black screen when compiling OpenMW for macOS 10.14

### ISSUE THREAD

**Issue by Thunderforge** [OpenMW/openmw-deps-mac#45]
When building OpenMW for macOS 10.14 while linking to the 2018-10-27 prebuilt dependencies (available [here](https://downloads.openmw.org/osx/dependencies/?C=M&O=D)), I get a completely black screen when launching the game. I can hear the audio, but there is no video at all. This does not happen with the October 17 OpenMW [nightly build](https://downloads.openmw.org/osx/nightly/?C=M&O=D), and my guess is that it's because it was built targeting an earlier version of macOS.

User spenguin on IRC noted the same issue; ever since upgrading to macOS 10.14, compiling OpenMW with prebuilt dependencies result in a black screen.

There is no console output to indicate an issue.

**Comment by nikolaykasyanov** [comment]
The black screen issue is fixed in macOS 10.14.2.

Btw, here's a new built of dependencies, now using macOS 10.14 SDK: 
http://downloads.openmw.org/osx/dependencies/openmw-deps-55c27b1.zip.

**UPD**: forgot to mention that I'll update OpenMW CI to use it soon.
