### ISSUE TITLE
Passing CMAKE_OSX_SYSROOT to MyGUI breaks build.

### ISSUE THREAD

**Issue by dwtj** [OpenMW/openmw-deps-mac#7]
- OS X 10.11.2
- Mac OS X 10.11.2
- Apple LLVM version 7.0.2 (clang-700.1.81) (Developer Tools)
- `openmw-deps-mac` 63005ac1
- CMake 3.4.1 (via Homebrew)
- QT5 (via Homebrew, Key-Only)

Attempts to build the `mygui` target of `openmw-deps-mac` a5e12316bf9eba5d3037ea19f711898523334859 crash on my machine. Here's the whole [build log](https://gist.github.com/dwtj/35d21538e2b6c3e68ede). Here's the relevant part of the output from `make mygui`.

```
  The C compiler "/Library/Developer/CommandLineTools/usr/bin/cc" is not able
  to compile a simple test program.

  It fails with the following output:

   Change Dir: /Users/dwtj/GitHub/dwtj/openmw-deps-mac-build/src/mygui-prefix/src/mygui-build/CMakeFiles/CMakeTmp



  Run Build Command:"/usr/bin/make" "cmTC_09655/fast"

  /Library/Developer/CommandLineTools/usr/bin/make -f
  CMakeFiles/cmTC_09655.dir/build.make CMakeFiles/cmTC_09655.dir/build

  Building C object CMakeFiles/cmTC_09655.dir/testCCompiler.c.o

  /Library/Developer/CommandLineTools/usr/bin/cc -isysroot macosx10.11
  -mmacosx-version-min=10.8 -o CMakeFiles/cmTC_09655.dir/testCCompiler.c.o -c
  /Users/dwtj/GitHub/dwtj/openmw-deps-mac-build/src/mygui-prefix/src/mygui-build/CMakeFiles/CMakeTmp/testCCompiler.c


  clang: warning: no such sysroot directory: 'macosx10.11'

  Linking C executable cmTC_09655

  /usr/local/Cellar/cmake/3.4.1/bin/cmake -E cmake_link_script
  CMakeFiles/cmTC_09655.dir/link.txt --verbose=1

  /Library/Developer/CommandLineTools/usr/bin/cc -isysroot macosx10.11
  -mmacosx-version-min=10.8 -Wl,-search_paths_first
  -Wl,-headerpad_max_install_names
  CMakeFiles/cmTC_09655.dir/testCCompiler.c.o -o cmTC_09655

  clang: warning: no such sysroot directory: 'macosx10.11'

  ld: library not found for -lSystem

  clang: error: linker command failed with exit code 1 (use -v to see
  invocation)
```

I am able to reproduce this same error message when building [MyGUI/mygui](https://github.com/MyGUI/mygui) (1a2bf4cf) with the following CMake parameters:

```
$ cmake
  -DCMAKE_INSTALL_PREFIX:PATH=/Users/dwtj/install.tmp \
  -DCMAKE_OSX_DEPLOYMENT_TARGET=10.8 \
  -DCMAKE_OSX_SYSROOT=macosx10.11 \
  -DPKG_CONFIG_USE_CMAKE_PREFIX_PATH=ON \
  -DCMAKE_MACOSX_RPATH=ON \
  -DMYGUI_RENDERSYSTEM=1 \
  -DMYGUI_BUILD_DEMOS=OFF \
  -DMYGUI_BUILD_TOOLS=OFF \
  -DMYGUI_BUILD_PLUGINS=OFF \
  ../mygui
$ make
```

However, when I remove the following two parameters, I am able to `make` `MyGUI/mygui` without any problems.

```
  -DCMAKE_OSX_DEPLOYMENT_TARGET=10.8 \
  -DCMAKE_OSX_SYSROOT=macosx10.11 \
```

Also, I believe that I am seeing the same symptom when compiling `bullet`, but I haven't verified that the cause seems to be `CMAKE_OSX_SYSROOT=macosx10.11`.

Let me know if you have any questions about this, or if you have any troubleshooting steps for me to try.

**Comment by dwtj** [comment]
This issue was resolved for me by installing the full version of XCode Version 7.2 (7C68). (Previously, I was using the command line developer tools.)

**Comment by nikolaykasyanov** [comment]
Thanks, I'll keep that in mind while writing readme for that repo. So probably command line tools are lacking OS X SDKs. Weird.

**Comment by nikolaykasyanov** [comment]
I added a README which recommends using Xcode, not Command Line Tools.
